src/Entity/Annonce.php
<?php

namespace App\Entity;

use App\Repository\AnnonceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=AnnonceRepository::class)
 * @ORM\Table(name="annonce", indexes={@ORM\Index(columns={"title","content"}, flags={"fulltext"})})
 */
class Annonce
{
    const LABEL_URGENT = "Urgent";
    const LABEL_PROMOTION = "Promotion";
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\NotNull
     */
    private $title;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\NotNull
     */
    private $price;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="boolean")
     * @Assert\NotNull
     */
    private $is_active = true;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotNull
     */
    private $etat = 'En ligne';

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="annonces")
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="annonces")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="annonce",cascade={"persist"})
     * @Assert\NotBlank
     */
    private $images;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="favoris")
     */
    private $favori;

    /**
     * @ORM\Column(type="integer")
     */
    private $vue;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $label;

    const etats=[
        'En attente'=>'En attente',
        'En ligne'=>'En ligne',
        'Hors ligne'=>'Hors ligne',
    ];
    const EN_ATTENTE = "En attente";

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->favori = new ArrayCollection();
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    public function getTitle(): ?string
    {
        return $this->title;
    }
    public function getSlug()
    {
        // return (new Slugify())->slugify($this->title);
        return str_replace(' ','_',$this->title);
    }

    public function setTitle(string $title): self
    {
        $this->title =ucfirst($title);

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content =ucfirst($content);

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(?string $etat): self
    {
        $this->etat =ucfirst($etat);

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAnnonce($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAnnonce() === $this) {
                $image->setAnnonce(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getFavori(): Collection
    {
        return $this->favori;
    }

    public function addFavori(User $favori): self
    {
        if (!$this->favori->contains($favori)) {
            $this->favori[] = $favori;
        }

        return $this;
    }

    public function removeFavori(User $favori): self
    {
        $this->favori->removeElement($favori);

        return $this;
    }

    public function getVue(): ?int
    {
        return $this->vue;
    }

    public function setVue(int $vue): self
    {
        $this->vue = $vue;

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(?string $label): self
    {
        $this->label = $label;

        return $this;
    }
}

src/Entity/Phone.php
<?php

namespace App\Entity;

use App\Repository\PhoneRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PhoneRepository::class)
 */
class Phone
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $number;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_whatsapp;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="phones")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(string $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getIsWhatsapp(): ?bool
    {
        return $this->is_whatsapp;
    }

    public function setIsWhatsapp(bool $is_whatsapp): self
    {
        $this->is_whatsapp = $is_whatsapp;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/AnnonceType.php
<?php

namespace App\Form;

use App\Entity\Annonce;
use App\Entity\Category;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnnonceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('price')
            ->add('content')
            ->add('category',EntityType::class,[
                'class'=>Category::class,
                'choice_label'=>'name'
                ])
            ->add('etat',ChoiceType::class,[
                'choices'=>Annonce::etats
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Annonce::class,
        ]);
    }
}

src/Controller/Admin/AnnonceController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Annonce;
use App\Form\AnnonceType;
use App\Repository\AnnonceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/annonce")
 */
class AnnonceController extends AbstractController
{
    /**
     * @Route("/", name="annonce_index", methods={"GET"})
     */
    public function index(AnnonceRepository $annonceRepository): Response
    {
        return $this->render('admin/annonce/index.html.twig', [
            'annonces' => $annonceRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="annonce_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $annonce = new Annonce();
        $form = $this->createForm(AnnonceType::class, $annonce);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($annonce);
            $entityManager->flush();

            return $this->redirectToRoute('annonce_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin/annonce/new.html.twig', [
            'annonce' => $annonce,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="annonce_show", methods={"GET"})
     */
    public function show(Annonce $annonce): Response
    {
        return $this->render('admin/annonce/show.html.twig', [
            'annonce' => $annonce,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="annonce_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Annonce $annonce): Response
    {
        $form = $this->createForm(AnnonceType::class, $annonce);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('annonce_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin/annonce/edit.html.twig', [
            'annonce' => $annonce,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="annonce_delete", methods={"POST"})
     */
    public function delete(Request $request, Annonce $annonce): Response
    {
        if ($this->isCsrfTokenValid('delete'.$annonce->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($annonce);
            $entityManager->flush();
        }

        return $this->redirectToRoute('annonce_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/MainController.php
<?php 
namespace App\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController{
    /**
     * @Route("/change-lang/{locale}", name="lang")
     */
    public function changeLocale($locale, Request $request)
    {
    
        $locale = $request->attributes->get('locale');
        
        $request->getSession()->set('_locale', $locale);
        
        $request->setLocale($request->getSession()->get('_locale', $locale));    
        
        return $this->redirect($request->headers->get('referer'));
    }
}

src/Controller/main/AnnonceController.php
<?php

namespace App\Controller\Main;

use App\Entity\Annonce;
use App\Entity\AnnonceSearch;
use App\Entity\CategoryParent;
use App\Form\AnnonceSearchType;
use App\Form\AppSearchType;
use App\Repository\AnnonceRepository;
use App\Repository\CategoryParentRepository;
use App\Repository\CategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use PhpParser\Node\Expr\Instanceof_;
use Symfony\Component\HttpFoundation\Request;

class AnnonceController extends AbstractController
{

    /**
     * @Route("/toutes-les-annonces", name="annonces")
     * @Route("/toutes-les-annonces/{parent}", name="annonces_parent")
     * @Route("/toutes-les-annonces/{parent}/{categorie}", name="annonces_categorie")
     */
    public function index(CategoryRepository $categoryRepository, AnnonceRepository $annonceRepository,string $categorie =null, string $parent = null,CategoryParentRepository $categoryParentRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $parentCategorie =  $parent = $categoryParentRepository->findOneBy([
                'name'=>$parent
            ]);
        $search = new AnnonceSearch();
        if($categorie){
            $categorie = str_replace('_',' ',$categorie);
            $categorie = $categoryRepository->findOneBy([
                'name'=>$categorie
            ]);
            $search->setCategory($categorie->getId());
        }        
        $form = $this->createForm(AppSearchType::class, $search)->handleRequest($request);
        
        $pagination = $paginator->paginate(
            $annonceRepository->search($search),
            $request->query->getInt('page',1),
            12
        );
        // $pagination = $paginator->paginate(
        //     $annonceRepository->parentCategorie($search),
        //     $request->query->getInt('page',1),
        //     12
        // );

        return $this->renderForm('main/annonce/index.html.twig', [
            'form'=>$form,
            'annonces' => $pagination,
            'parent'=>$parentCategorie,
            'parents'=>$categoryParentRepository->findAll()
        ]);
    }
    /**
     * @Route("/annonces-details/{slug}/{id}", name="annonce_detail")
     */
    public function show(Annonce $annonce, string $slug): Response
    {
        if($slug !== $annonce->getSlug()){
            return $this->redirectToRoute('annonce_detail',[
                'slug'=>$annonce->getSlug(),
                'id'=>$annonce->getId()
            ],301);
        }
        return $this->renderForm('main/annonce/detail.html.twig', [
            'annonce'=>$annonce
        ]);
    }
}

src/Controller/main/HomeController.php
<?php

namespace App\Controller\Main;

use App\Entity\AnnonceSearch;
use App\Form\AppSearchType;
use App\Repository\CategoryParentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(CategoryParentRepository $categoryParentRepository, Request $request): Response
    {
        $search = new AnnonceSearch();
        $form = $this->createForm(AppSearchType::class, $search)->handleRequest($request);

        return $this->renderForm('main/home/index.html.twig', [
            'form'=>$form,
            'parents'=>$categoryParentRepository->findAll()

        ]);
    }
}

templates/main/annonce/_annonce.html.twig
{% for item in items %}
<div class="row mt-2 p-2 bg-white border rounded">
    <div class="col-md-2 col-3 mt-1 annonce-card-img">
        <img class="img-fluid img-responsive annonce-img rounded product-image"
            src="{{ asset('img/annonce/vide.png') }}">
        <div class="annonce-card-nbr">
            <span>
                <i class="fa fa-camera text-dark" aria-hidden="true"></i>
                {{item.images|length}}
            </span>
            <span><i class="fa fa-eye text-dark" aria-hidden="true"></i>
                {{ item.vue}}
            </span>
        </div>

    </div>
    <div class="col-md-7 col-9 mt-1">
        <a class="a-detail" href="{{ path('annonce_detail',{slug:item.slug,id:item.id}) }}">
            <h5 class="text-truncate annonce-title">{{ item.title }}</h5>
            <div class="d-flex flex-row align-items-center">
                <h4 class="mr-1 text-danger font-weight-bold annonce-price">{{ item.price|number_format(0,'',' ') ~ ' '
                    ~
                    site.current_name }}</h4>

                {% if item.label is not null %}
                <div class="d-flex flex-row annonce-label">
                    <span class="text-warning font-weight-bold">
                        {{ item.label }}
                    </span>
                </div>
                {% endif %}
            </div>
            <p class="para mb-0 annonce-content">{{ item.content|slice(0,110) }} {{ item.content|length > 110 ?
                '[...]':''}} <br></p>
            <div class="mb-1 spec-1 annonce-details">
                <span>{{item.category.name}}</span> | <br>
                <span><i class="fas fa-map-marked-alt text-dark"></i> {{ item.user.adresse }} -  le {{
                    item.createdAt|date_format_min_fr }}</span>
            </div>
        </a>
    </div>
    <div class="align-items-center align-content-center col-md-3 col-12 border-left mt-1">
        <h6 class="text-success annonce-compte">{{item.user.compte}}</h6>
        <div class="d-flex flex-column mt-1 annonce-card-action">
            <button class="btn btn-primary btn-sm annonce-btn-message" type="button"><i class="fa fa-comments"
                    aria-hidden="true"></i>
                Message
            </button>
            {% if item.user.phones[0] is not empty %}
                {% if item.user.phones[0].isWhatsapp %}
                <button class="btn btn-success mt-2 btn-sm annonce-btn-whatsapp" type="button"> <i
                    class="fab fa-whatsapp"></i> Message
                    Whatsapp
                </button>
                {% endif %}
            <button class="btn btn-outline-primary btn-sm mt-2 annonce-btn-appeller" type="button">
                <i class="fas fa-phone"></i>
                {{ item.user.phones[0].number |phone_format }}
            </button>
            {% endif %}
        </div>
    </div>
</div>
{% endfor %}

templates/main/annonce/_annonce1.html.twig
{% for item in items %}
<div class=" col-md-6 annonce-desktop col-12 isotope-item Ordinateur mobile-text "
    style="position: absolute; left: 0%; top: 0px;">
    <div class="card mb-1 border-primar overflow-hidden" style="max-width: 590px;">
        <div class="row no-gutters">
            <div class="col-md-4 col-4 align-self-center overflow-hidden ">
                <img src="/public/img/annonces/annonce-29-img-1.jpg"
                    style="width:100%;height:180px;object-fit: cover; object-position: bottom;"
                    class=" align-middle d-block mx-auto" alt="photo manquante">
            </div>
            <div class="col-md-8 col-8 ">
                <div class="card-body">
                    <!-- Tittre  -->
                    <a href="/publication-detail-Connecteur_disque_dur-29" class="text-secondary" data-toggle="tooltip"
                        data-placement="left" title="" data-original-title="Visualiser l'annonce">
                        <h5 class="font-weight-bold text-capitalize text-truncate card-title name">
                            Connecteur disque dur </h5>
                    </a>

                    <!-- prix -->
                    <p class="card-text text-danger font-weight-bold ">5 000 F cfa <span
                            class="prix visible-false ">5000</span></p>
                    <!-- description -->

                    <p class="card-text text-dark"> <a class="hov-cl1 publication-detail " data-toggle="tooltip"
                            data-placement="left" title="" href="/publication-detail-Connecteur_disque_dur-29"
                            data-original-title="Plus de detail">Connecte ton disque dure facilement</a></p>

                    <!-- date de creation -->


                    <!-- info annonceur -->
                    <!-- <p class="card-text text-annonce text-truncate">
                            <span data-toggle="tooltip" data-placement="top" title="Adresse de l'annonceur">
                                <i class="fa fa-map-marker" aria-hidden="true"></i> Sacre coeur 2 </span>
                        </p> -->
                    <p class="card-text footer-annonce">
                        <!-- NB IMAGES -->
                        <a href="/publication-detail-Connecteur_disque_dur-29" class="text-secondary"
                            data-toggle="tooltip" data-placement="top" title="" data-original-title="Nombre d'images">
                            <i class="fa fa-camera" aria-hidden="true"></i> 1 |
                        </a>
                        <!-- NB VUEW -->
                        <a href="/publication-detail-Connecteur_disque_dur-29" class="text-secondary"
                            data-toggle="tooltip" data-placement="top" title="" data-original-title="Nombre de vues">
                            <i class="fa fa-eye" aria-hidden="true"></i>
                            66 </a>
                        |
                        <!-- CATEGORIE -->
                        <span class="text-secondary categorie" data-toggle="tooltip" data-placement="top" title=""
                            data-original-title="Catégorie">
                            Informatique </span>
                        |
                        <span data-toggle="tooltip" data-placement="top" title=""
                            data-original-title="Adresse de l'annonceur">
                            <i class="fa fa-map-marker" aria-hidden="true"></i> Sacre coeur 2 </span>

                    </p>
                    <p class="card-text"><small class="text-muted">Publier le mardi 20 juillet 2021 </small>
                    </p>
                </div>

            </div>
        </div>
    </div>
</div>
{% endfor %}

templates/main/annonce/_annonce2.html.twig
{% for item in items %}
<div class="row mt-2 p-2 bg-white border rounded">
    <div class="col-md-3 mt-1"><img class="img-fluid img-responsive rounded product-image"
            src="img/annonce/vide.png"></div>
    <div class="col-md-5 mt-1">
        <h5>{{ item.title }}</h5>
        <div class="d-flex flex-row">
            <div class="ratings mr-2"><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i
                    class="fa fa-star"></i></div><span>310</span>
        </div>
        {# <div class="mt-1 mb-1 spec-1"><span>100% cotton</span><span class="dot"></span><span>Light weight</span><span
                class="dot"></span><span>Best finish<br></span></div>
        <div class="mt-1 mb-1 spec-1"><span>Unique design</span><span class="dot"></span><span>For men</span><span
                class="dot"></span><span>Casual<br></span></div> #}
        <p class="text-justify text-truncate para mb-0">{{ item.content }}<br><br></p>
    </div>
    <div class="align-items-center align-content-center col-md-4 border-left mt-1">
        <div class="d-flex flex-row align-items-center">
            <h4 class="mr-1">{{ item.price|number_format(0,'',' ') ~ ' ' ~ site.current_name }}</h4>
        </div>
        <h6 class="text-success">Free shipping</h6>
        <div class="d-flex flex-column mt-4">
            <button class="btn btn-primary btn-sm" type="button">Details</button>
            <button class="btn btn-outline-primary btn-sm mt-2" type="button">
            Add to Contacter
            </button>
        </div>
    </div>
</div>
{% endfor %}

templates/main/annonce/_user_action.html.twig
<div class="d-flex flex-column mt-1 annonce-card-action">
    <button class="btn btn-primary btn-sm annonce-btn-message" type="button"><i class="fa fa-comments"
            aria-hidden="true"></i>
        Message
    </button>
    {% if item.user.phones[0] is not empty %}
        {% if item.user.phones[0].isWhatsapp %}
        <button class="btn btn-success mt-2 btn-sm annonce-btn-whatsapp" type="button"> <i
            class="fab fa-whatsapp"></i> Message
            Whatsapp
        </button>
        {% endif %}
    <button class="btn btn-outline-primary btn-sm mt-2 annonce-btn-appeller" type="button">
        <i class="fas fa-phone"></i>
        {{ item.user.phones[0].number |phone_format }}
    </button>
    {% endif %}
</div>

templates/main/annonce/detail.html.twig
{% extends "base.html.twig" %}
{% block title %}
    {{ annonce.title }}
{% endblock %}
{% block body %}
<style>
    .annonce-detail {
        font-size: 14px;
        letter-spacing: 1px;
    }

    .annonce-detail-card-user-img {
        text-align: center;
    }

    .annonce-detail-img {
        border-radius: 50%;
        text-align: center;
    }

    .annonce-detail-card-user {
        background-color: #fff;
        padding: 5px;
    }

    .annonce-detail-card-user-name {
        text-align: center;
    }

    .annonce-detail-card-img {
        text-align: center;
    }

    .annonce-detail-card-img img {
        /* width: 100%; */
    }
</style>
<div class="container bg-white">
    <div class="row py-3 annonce-detail">
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-8">
                    <div>
                        <div class="annonce-detail-card-img">
                            <img src="https://via.placeholder.com/300" alt="" srcset="">
                        </div>
                        <div>
                            <span>
                                <i class="fa fa-camera text-dark" aria-hidden="true"></i>
                                {{annonce.images|length}}
                            </span>
                            <span><i class="fa fa-eye text-dark" aria-hidden="true"></i>
                                {{ annonce.vue}}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div>
                    <h4 class="annonce-detail-title">{{ annonce.title }}</h4>
                    <p class="annonce-detail-price">
                        {{ annonce.price|number_format(0,'',' ') ~ ' ' ~ site.current_name }}
                    </p>
                    <p class="annonce-detail-desc">
                        {{ annonce.content }}
                    </p>
                      Categorie: <span>{{annonce.category.name}}</span>
                    <div>
                        <span><i class="fas fa-map-marked-alt text-dark"></i> {{ annonce.user.adresse }} - le {{
                            annonce.createdAt|date_format_min_fr }}</span>
                    </div>
                </div>

                <div>
                    <a type="button">
                        Copie le le lien <i class="fas fa-copy"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="annonce-detail-card-user">
                <div class="annonce-detail-card-user-img">
                    <img src="https://via.placeholder.com/100" class="annonce-detail-img">
                </div>
                <p class="annonce-detail-card-user-name">Malick Tounkara</p>
                <p>
                    Adresse: Dakar Sacre coeur 2
                </p>
                <p>Compte : Professionnel</p>
                <p>Nombre annonces: 0</p>
                <a href="#">Cette annonceur a aussi publié</a>
                <p>78 127 92 82 - 78 772 82 99 - 77 838 88 88</p>
                <div>
                    <div class="d-flex flex-column mt-1 annonce-card-action">
                        <button class="btn btn-primary btn-sm annonce-btn-message" type="button"><i class="fa fa-comments"
                                aria-hidden="true"></i>
                            Message
                        </button>
                        {% if annonce.user.phones[0] is not empty %}
                            {% if annonce.user.phones[0].isWhatsapp %}
                            <button class="btn btn-success mt-2 btn-sm annonce-btn-whatsapp" type="button"> <i
                                class="fab fa-whatsapp"></i> Message
                                Whatsapp
                            </button>
                            {% endif %}
                        <button class="btn btn-outline-primary btn-sm mt-2 annonce-btn-appeller" type="button">
                            <i class="fas fa-phone"></i>
                            {{ annonce.user.phones[0].number |phone_format }}
                        </button>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>
{% endblock %}